export const PERSON_POLICEMAN_COLLIDE = 'PERSON_POLICEMAN_COLLIDE';
export const PERSON_POLICEMAN_REMOVE = 'PERSON_POLICEMAN_REMOVE';

export const ENEMY_COLLIDE = 'ENEMY_COLLIDE';

export const REDUCE_MOOD = 'REDUCE_MOOD';
export const INCREASE_MOOD = 'INCREASE_MOOD';

export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_MONEY = 'UPDATE_MONEY';


export const ADD_CACTUS = 'ADD_CACTUS';
export const THROW_CACTUS = 'THROW_CACTUS';

export const COLLIDE_POLICEMAN_CACTUS = 'COLLIDE_POLICEMAN_CACTUS';

export const GAME_OVER = 'GAME_OVER'

export const COLLIDE_OFFICIAL = 'COLLIDE_OFFICIAL'
export const COLLIDE_PASSER = 'COLLIDE_PASSER'