export const PERSON_POLICEMAN_COLLIDE = 'PERSON_POLICEMAN_COLLIDE';
export const PERSON_POLICEMAN_REMOVE = 'PERSON_POLICEMAN_REMOVE';

export const ENEMY_COLLIDE = 'ENEMY_COLLIDE';

export const REDUCE_MOOD = 'REDUCE_MOOD';
export const INCREASE_MOOD = 'INCREASE_MOOD';